on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: "1.18"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: go test
        run: go test ./...
