name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - uses: golangci/golangci-lint-action@v2

      - name: go test
        run: go test ./... -coverpkg=./... -covermode=count -timeout=30s -coverprofile=coverage.txt

      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
